name: Download and Execute Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display current directory and list contents (after checkout)
      run: |
        pwd
        ls -l

    - name: Install aria2
      run: sudo apt-get install -y aria2

    - name: Download file
      run: |
        aria2c https://fireos-tablet-src.s3.amazonaws.com/8K49yrsysRiOpSw671IlXTNGMr/Fire_HD8_10th_Gen-7.3.1.9-20210412.tar.bz2 -o Fire_HD8_10th_Gen-7.3.1.9-20210412.tar.bz2
        pwd
        ls -l

    - name: Extract tar.bz2 file
      run: |
        tar -xjf Fire_HD8_10th_Gen-7.3.1.9-20210412.tar.bz2
        pwd
        ls -l

    - name: Extract build_kernel.tar.gz
      run: |
        tar -xzf build_kernel.tar.gz
        pwd
        ls -l

    - name: Run build_kernel.sh
      run: |
        pwd
        ls -l
        ./build_kernel.sh platform.tar output
        
