name: Download and Execute Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display current directory and list contents (after checkout)
      run: |
        pwd
        ls -l

    - name: Install aria2
      run: sudo apt-get install -y aria2

    - name: Download file
      run: |
        aria2c https://fireos-tablet-src.s3.amazonaws.com/8K49yrsysRiOpSw671IlXTNGMr/Fire_HD8_10th_Gen-7.3.1.9-20210412.tar.bz2 -o Fire_HD8_10th_Gen-7.3.1.9-20210412.tar.bz2
        pwd
        ls -l

    - name: Extract tar.bz2 file
      run: |
        tar -xjf Fire_HD8_10th_Gen-7.3.1.9-20210412.tar.bz2
        pwd
        ls -l

    - name: Extract build_kernel.tar.gz
      run: |
        tar -xzf build_kernel.tar.gz
        pwd
        ls -l

    - name: Setup clang 6.0.2
      run: |
        sed -i 's|CLANG_COMPILER_PATH=""|CLANG_COMPILER_PATH='"$(pwd)"'/prebuilt|' build_kernel_config.sh
        echo  "Downloading clang 6.0.1"
        # Set up variables
        CLANG_VERSION="6.0.1"
        CLANG_DIR="prebuilt"
        CLANG_BIN_DIR="${CLANG_DIR}/bin"
        CLANG_TAR="clang+llvm-${CLANG_VERSION}-x86_64-linux-gnu-ubuntu-16.04.tar.xz"
        CLANG_URL="http://releases.llvm.org/${CLANG_VERSION}/${CLANG_TAR}"
        CLANG_EXTRACT_DIR="clang+llvm-${CLANG_VERSION}-x86_64-linux-gnu"
    
        # Create necessary directories
        mkdir -p ${CLANG_BIN_DIR}
    
        # Download and extract clang
        echo "Downloading clang ${CLANG_VERSION}"
        curl -LO ${CLANG_URL}
        tar -xf ${CLANG_TAR}
    
        # Move clang binary to the prebuilt/bin directory
        mv ${CLANG_EXTRACT_DIR}/bin/clang ${CLANG_BIN_DIR}/clang
    
        # Clean up
        rm -rf ${CLANG_EXTRACT_DIR} ${CLANG_TAR}
        

        
    - name: Run build_kernel.sh
      run: |
        pwd
        ls -l
        ./build_kernel.sh platform.tar output
        
